-- MySQL Script generated by MySQL Workbench
-- Wed Mar 23 18:24:49 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DER_Sustech
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DER_Sustech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DER_Sustech` DEFAULT CHARACTER SET utf8 ;
USE `DER_Sustech` ;

-- -----------------------------------------------------
-- Table `DER_Sustech`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER_Sustech`.`usuario` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(255) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `foto` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER_Sustech`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER_Sustech`.`Categoria` (
  `id` BIGINT NOT NULL,
  `tipo` VARCHAR(255) NOT NULL,
  `palavrachave` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DER_Sustech`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DER_Sustech`.`produto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(500) NOT NULL,
  `quantidade` INT NOT NULL,
  `preco` DECIMAL(10,2) NOT NULL,
  `estado` VARCHAR(255) NOT NULL,
  `usuario_id` BIGINT NOT NULL,
  `Categoria_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`, `Categoria_id`),
  INDEX `fk_produto_usuario_idx` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_produto_Categoria1_idx` (`Categoria_id` ASC) VISIBLE,
  CONSTRAINT `fk_produto_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `DER_Sustech`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_produto_Categoria1`
    FOREIGN KEY (`Categoria_id`)
    REFERENCES `DER_Sustech`.`Categoria` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
